#!/usr/bin/env node
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const args = parseArgs(process.argv.slice(2));
const outDir = path.resolve(args.out ?? ".bench/fifty-stage-rest");
const stageCount = Number.parseInt(args.stages ?? "50", 10);
const profile = args.profile ?? "basic";

if (!Number.isInteger(stageCount) || stageCount <= 0) {
  throw new Error(`--stages must be a positive integer, got ${args.stages}`);
}
if (!["basic", "api", "api-compute"].includes(profile)) {
  throw new Error(`--profile must be basic, api, or api-compute, got ${profile}`);
}

await mkdir(outDir, { recursive: true });
await mkdir(path.join(outDir, "project-plan"), { recursive: true });
await mkdir(path.join(outDir, "src"), { recursive: true });
await mkdir(path.join(outDir, "inventory"), { recursive: true });

const created = new Date().toISOString();
const stageIds = Array.from({ length: stageCount }, (_, index) =>
  `stage-${String(index + 1).padStart(2, "0")}`,
);

await writeFile(path.join(outDir, "PLAN.md"), buildPlan(stageIds, created), "utf8");
await writeFile(path.join(outDir, "DIRECTIVES.md"), buildDirectives(outDir, stageCount, created, profile), "utf8");
await writeFile(path.join(outDir, "JOURNAL.md"), buildJournal(stageCount, created), "utf8");
await writeFile(path.join(outDir, "INVENTORY.md"), buildInventory(), "utf8");
await writeFile(path.join(outDir, "src", ".gitkeep"), "", "utf8");

for (const [index, stageId] of stageIds.entries()) {
  await writeFile(
    path.join(outDir, "project-plan", `${stageId}.md`),
    buildStage(stageId, index + 1, stageIds[index - 1], created, profile),
    "utf8",
  );
}

console.log(`Generated ${stageCount}-stage InfiniClaw fixture at ${outDir}`);

function buildPlan(ids, createdAt) {
  const lines = [
    "# PLAN - 50-Stage REST Synthetic",
    "schema_version: 1",
    `created: ${createdAt}`,
    `last_replanned: ${createdAt}`,
    "status: ACTIVE",
    "owner: main",
    `turn_budget_total: ${ids.length * 20}`,
    "cost_budget_usd: 25.00",
    "",
    "## Goal",
    `Seal ${ids.length} deterministic REST-style stages without losing state across compactions.`,
    "",
    "## High-Level Definition of Done",
    "- type: file_exists",
    `  path: src/${ids.at(-1)}.mjs`,
    "- type: fs_size_under",
    "  path: JOURNAL.md",
    "  max_bytes: 10000",
    "",
    "## Stages",
  ];

  for (const [index, id] of ids.entries()) {
    const depends = index === 0 ? "" : ` | depends: [${ids[index - 1]}]`;
    lines.push(`${index + 1}. ${id} | PENDING${depends}`);
  }

  lines.push(
    "",
    "## Sealed Outputs Registry",
    "# (empty)",
    "",
    "## Global Constraints",
    "- Consult INVENTORY.md before each new module.",
    "- Do not edit DIRECTIVES.md.",
    "- Keep every stage output small and mechanically verifiable.",
    "",
    "## Notes",
    "Synthetic fixture generated by bench/synthetic/fifty-stage-rest/generate-fixture.mjs.",
  );
  return `${lines.join("\n")}\n`;
}

function buildDirectives(workspace, stageCountValue, createdAt, profileName) {
  return `# DIRECTIVES (immutable for this agent's lifetime)
schema_version: 1
agent: main
parent: null
workspace: ${workspace}
spawned: ${createdAt}
journal: ./JOURNAL.md

## GOAL
Execute and seal the generated ${stageCountValue}-stage REST synthetic plan (${profileName} profile).

## INPUT CONTRACT
- path: PLAN.md
- path: project-plan/
- path: INVENTORY.md

## OUTPUT CONTRACT
- kind: project
  path: PLAN.md
  exports: []
  interface: "All stages sealed with verifier-gated outputs"

## DEFINITION OF DONE
- type: file_exists
  path: PLAN.md
- type: file_exists
  path: INVENTORY.md
- type: fs_size_under
  path: JOURNAL.md
  max_bytes: 10000

## CONSTRAINTS
- Treat DIRECTIVES.md as immutable.
- Consult INVENTORY.md before creating each new implementation file.
- Only mark a step DONE after verifier allPass for that exact step.

## TURN BUDGET
max_turns: ${stageCountValue * 20}
warning_at: ${Math.floor(stageCountValue * 16)}
escalate_at: ${Math.floor(stageCountValue * 19)}

## INITIAL DECOMPOSITION
- step-1: Activate and seal stage files in order
- step-2: Check final plan and journal bounds

## PROTOCOL
You are an OpenClaw agent under the Persistent Directive System.
`;
}

function buildJournal(stageCountValue, createdAt) {
  return `# JOURNAL
schema_version: 1
agent: main
last_updated: ${createdAt}
turns_used: 0
max_turns: ${stageCountValue * 20}
warning_at: ${Math.floor(stageCountValue * 16)}
escalate_at: ${Math.floor(stageCountValue * 19)}
last_verifier_run: null

## TASK STACK

#### step-1: Activate and seal stage files in order
status: IN_PROGRESS
started: ${createdAt}
progress: Fixture generated; no stages sealed yet.
blocker: null

#### step-2: Check final plan and journal bounds
status: PENDING

## WORKING NOTES
# (empty)

## SUB-AGENTS
# (empty)

## COMPLETION REPORT
# Written once, at TASK_COMPLETE. Empty until then.
`;
}

function buildInventory() {
  return `# INVENTORY
schema_version: 1
# One line per sealed output. Append-only. Sorted by stage order, not time.

`;
}

function buildStage(stageId, ordinal, previousStageId, createdAt, profileName) {
  if (profileName === "api-compute") {
    return buildApiComputeStage(stageId, ordinal, previousStageId, createdAt);
  }
  if (profileName === "api") {
    return buildApiStage(stageId, ordinal, previousStageId, createdAt);
  }
  return buildBasicStage(stageId, ordinal, previousStageId, createdAt);
}

function buildBasicStage(stageId, ordinal, previousStageId, createdAt) {
  const functionName = basicFunctionName(ordinal);
  const outputPath = `src/${stageId}.mjs`;
  const servicePath = `inventory/${stageId}.md`;
  const command = `node -e "import(\\"./${outputPath}\\").then((m)=>{if(m.${functionName}()!==\\"${stageId}\\")process.exit(1)}).catch(()=>process.exit(1))"`;
  return `# Stage ${String(ordinal).padStart(2, "0")} - Synthetic endpoint ${ordinal}
schema_version: 1
status: PENDING
created: ${createdAt}
activated: null
sealed: null
turn_budget: 20

## Depends On
${previousStageId ? `- service: inventory/${previousStageId}.md` : "# (empty)"}

## Output Contract
- kind: file
  path: ${outputPath}
  exports:
    - ${functionName}
  interface: "export function ${functionName}(): string"
- kind: service
  path: ${servicePath}
  exports: []
  interface: "${stageId} sealed output card"

## Definition of Done
- type: file_exists
  path: ${outputPath}
- type: grep_present
  path: ${outputPath}
  pattern: "export\\\\s+function\\\\s+${functionName}"
- type: shell_exit_zero
  cmd: ${yamlSingle(command)}
- type: grep_absent
  path: ${outputPath}
  pattern: "TODO|FIXME|console\\\\.log"

## Sub-Tasks
A:
  id: ${stageId}.A
  goal: "Implement ${functionName} in ${outputPath}"
  input_contract:
${previousStageId ? `    - service: inventory/${previousStageId}.md` : "    - path: PLAN.md"}
  output_contract:
    - path: ${outputPath}
  can_start: immediately
  turn_budget: 12
  preset: software-implementation

## Context for Sub-Agents
- Return exactly "${stageId}" from ${functionName}.
- Keep the file dependency-free.

## Execution Log
# (empty)

## SEALED SUMMARY
# (empty)
`;
}

function buildApiStage(stageId, ordinal, previousStageId, createdAt) {
  const functionName = apiFunctionName(ordinal);
  const outputPath = `src/${stageId}.mjs`;
  const servicePath = `inventory/${stageId}.md`;
  const route = `/api/${stageId}`;
  const token = `${stageId}-token`;
  const command = buildApiVerifierCommand(outputPath, functionName, {
    stageId,
    route,
    token,
    ordinal,
  });
  return `# Stage ${String(ordinal).padStart(2, "0")} - Synthetic API endpoint ${ordinal}
schema_version: 1
status: PENDING
created: ${createdAt}
activated: null
sealed: null
turn_budget: 24

## Depends On
${previousStageId ? `- service: inventory/${previousStageId}.md` : "# (empty)"}

## Output Contract
- kind: file
  path: ${outputPath}
  exports:
    - ${functionName}
  interface: "export function ${functionName}(request): { status: number, body: object }"
- kind: service
  path: ${servicePath}
  exports: []
  interface: "${stageId} API handler sealed output card"

## Definition of Done
- type: file_exists
  path: ${outputPath}
- type: grep_present
  path: ${outputPath}
  pattern: "export\\\\s+function\\\\s+${functionName}"
- type: shell_exit_zero
  cmd: ${yamlSingle(command)}
- type: grep_absent
  path: ${outputPath}
  pattern: "TODO|FIXME|console\\\\.log|fetch\\\\(|import\\\\s"

## Sub-Tasks
A:
  id: ${stageId}.A
  goal: "Implement ${functionName} in ${outputPath}"
  input_contract:
${previousStageId ? `    - service: inventory/${previousStageId}.md` : "    - path: PLAN.md"}
  output_contract:
    - path: ${outputPath}
  can_start: immediately
  turn_budget: 16
  preset: software-implementation

## Context for Sub-Agents
- Implement a pure dependency-free JavaScript API handler.
- Required route: ${route}
- Required method: POST
- Required authorization header: Bearer ${token}
- Valid body: { "id": "${stageId}", "value": ${ordinal} }
- Valid response: { status: 200, body: { ok: true, route: "${route}", id: "${stageId}", value: ${ordinal}, checksum: "${stageId}:${ordinal}" } }
- Missing/invalid authorization returns { status: 401, body: { error: "unauthorized" } }
- Wrong method or path returns { status: 404, body: { error: "not_found" } }
- Invalid body returns { status: 400, body: { error: "bad_request" } }

## Execution Log
# (empty)

## SEALED SUMMARY
# (empty)
`;
}

function buildApiComputeStage(stageId, ordinal, previousStageId, createdAt) {
  const functionName = apiFunctionName(ordinal);
  const outputPath = `src/${stageId}.mjs`;
  const servicePath = `inventory/${stageId}.md`;
  const route = `/api/${stageId}/compute`;
  const token = `${stageId}-token`;
  const modulus = 997;
  const checkModulus = ordinal + 5;
  const command = buildApiComputeVerifierCommand(outputPath, functionName, {
    stageId,
    route,
    token,
    ordinal,
    modulus,
    checkModulus,
  });
  return `# Stage ${String(ordinal).padStart(2, "0")} - Synthetic compute API endpoint ${ordinal}
schema_version: 1
status: PENDING
created: ${createdAt}
activated: null
sealed: null
turn_budget: 28

## Depends On
${previousStageId ? `- service: inventory/${previousStageId}.md` : "# (empty)"}

## Output Contract
- kind: file
  path: ${outputPath}
  exports:
    - ${functionName}
  interface: "export function ${functionName}(request): { status: number, body: object }"
- kind: service
  path: ${servicePath}
  exports: []
  interface: "${stageId} compute API handler sealed output card"

## Definition of Done
- type: file_exists
  path: ${outputPath}
- type: grep_present
  path: ${outputPath}
  pattern: "export\\\\s+function\\\\s+${functionName}"
- type: shell_exit_zero
  cmd: ${yamlSingle(command)}
- type: grep_absent
  path: ${outputPath}
  pattern: "TODO|FIXME|console\\\\.log|fetch\\\\(|import\\\\s"

## Sub-Tasks
A:
  id: ${stageId}.A
  goal: "Implement ${functionName} in ${outputPath}"
  input_contract:
${previousStageId ? `    - service: inventory/${previousStageId}.md` : "    - path: PLAN.md"}
  output_contract:
    - path: ${outputPath}
  can_start: immediately
  turn_budget: 18
  preset: software-implementation

## Context for Sub-Agents
- Implement a pure dependency-free JavaScript compute API handler.
- Required route: ${route}
- Required method: POST
- Required authorization header: Bearer ${token}
- Valid body shape is exactly { "id": "${stageId}", "value": integer, "values": [integer, integer, integer], "mode": "sum" | "mix" }
- For mode "sum": result = value + values[0] + values[1] + values[2] + ${ordinal}
- For mode "mix": result = ((value * ${ordinal + 3}) + values[0] - values[1] + values[2]) modulo ${modulus}, normalized to 0..${modulus - 1}
- Valid response: { status: 200, body: { ok: true, route: "${route}", id: "${stageId}", mode, result, checksum } }
- Checksum formula: "${stageId}:" + mode + ":" + result + ":" + (result modulo ${checkModulus})
- Missing/invalid authorization returns { status: 401, body: { error: "unauthorized" } }
- Wrong method or path returns { status: 404, body: { error: "not_found" } }
- Invalid body returns { status: 400, body: { error: "bad_request" } }

## Execution Log
# (empty)

## SEALED SUMMARY
# (empty)
`;
}

function buildApiVerifierCommand(outputPath, functionName, spec) {
  const script = `
import("./${outputPath}").then((m)=>{
  const handler = m.${functionName};
  if (typeof handler !== "function") process.exit(1);
  const cases = [
    ["valid", { method: "POST", path: "${spec.route}", headers: { authorization: "Bearer ${spec.token}" }, body: { id: "${spec.stageId}", value: ${spec.ordinal} } }, 200, { checksum: "${spec.stageId}:${spec.ordinal}", route: "${spec.route}" }],
    ["missing-auth", { method: "POST", path: "${spec.route}", headers: {}, body: { id: "${spec.stageId}", value: ${spec.ordinal} } }, 401, { error: "unauthorized" }],
    ["wrong-method", { method: "GET", path: "${spec.route}", headers: { authorization: "Bearer ${spec.token}" }, body: { id: "${spec.stageId}", value: ${spec.ordinal} } }, 404, { error: "not_found" }],
    ["wrong-path-before-auth", { method: "POST", path: "${spec.route}/extra", headers: {}, body: { id: "${spec.stageId}", value: ${spec.ordinal} } }, 404, { error: "not_found" }],
    ["wrong-value", { method: "POST", path: "${spec.route}", headers: { authorization: "Bearer ${spec.token}" }, body: { id: "${spec.stageId}", value: -1 } }, 400, { error: "bad_request" }],
    ["extra-body-field", { method: "POST", path: "${spec.route}", headers: { authorization: "Bearer ${spec.token}" }, body: { id: "${spec.stageId}", value: ${spec.ordinal}, extra: true } }, 400, { error: "bad_request" }],
  ];
  for (const [label, request, status, bodySubset] of cases) {
    const response = handler(request);
    if (response?.status !== status) {
      console.error(label + ": expected status " + status + ", got " + response?.status);
      process.exit(1);
    }
    for (const [key, value] of Object.entries(bodySubset)) {
      if (response?.body?.[key] !== value) {
        console.error(label + ": expected body." + key + " " + JSON.stringify(value) + ", got " + JSON.stringify(response?.body?.[key]));
        process.exit(1);
      }
    }
  }
}).catch(()=>process.exit(1))
`;
  return `node -e ${JSON.stringify(script.replace(/\s+/gu, " ").trim())}`;
}

function buildApiComputeVerifierCommand(outputPath, functionName, spec) {
  const script = `
import("./${outputPath}").then((m)=>{
  const handler = m.${functionName};
  if (typeof handler !== "function") process.exit(1);
  const expected = (mode, value, values) => {
    const result = mode === "sum"
      ? value + values[0] + values[1] + values[2] + ${spec.ordinal}
      : (((value * ${spec.ordinal + 3}) + values[0] - values[1] + values[2]) % ${spec.modulus} + ${spec.modulus}) % ${spec.modulus};
    return { mode, result, checksum: "${spec.stageId}:" + mode + ":" + result + ":" + (result % ${spec.checkModulus}) };
  };
  const validCases = [
    ["valid-sum", { method: "POST", path: "${spec.route}", headers: { authorization: "Bearer ${spec.token}" }, body: { id: "${spec.stageId}", value: ${spec.ordinal}, values: [1, 2, 3], mode: "sum" } }, expected("sum", ${spec.ordinal}, [1, 2, 3])],
    ["valid-mix", { method: "POST", path: "${spec.route}", headers: { authorization: "Bearer ${spec.token}" }, body: { id: "${spec.stageId}", value: ${spec.ordinal + 7}, values: [${spec.ordinal + 1}, ${spec.ordinal + 4}, ${spec.ordinal + 9}], mode: "mix" } }, expected("mix", ${spec.ordinal + 7}, [${spec.ordinal + 1}, ${spec.ordinal + 4}, ${spec.ordinal + 9}])],
  ];
  for (const [label, request, expectedBody] of validCases) {
    const response = handler(request);
    if (response?.status !== 200) {
      console.error(label + ": expected status 200, got " + response?.status);
      process.exit(1);
    }
    for (const key of ["route", "id", "mode", "result", "checksum"]) {
      const expectedValue = key === "route" ? "${spec.route}" : key === "id" ? "${spec.stageId}" : expectedBody[key];
      if (response?.body?.[key] !== expectedValue) {
        console.error(label + ": expected body." + key + " " + JSON.stringify(expectedValue) + ", got " + JSON.stringify(response?.body?.[key]));
        process.exit(1);
      }
    }
  }
  const badCases = [
    ["missing-auth", { method: "POST", path: "${spec.route}", headers: {}, body: { id: "${spec.stageId}", value: ${spec.ordinal}, values: [1, 2, 3], mode: "sum" } }, 401, "unauthorized"],
    ["wrong-path-before-auth", { method: "POST", path: "${spec.route}/extra", headers: {}, body: { id: "${spec.stageId}", value: ${spec.ordinal}, values: [1, 2, 3], mode: "sum" } }, 404, "not_found"],
    ["wrong-method", { method: "GET", path: "${spec.route}", headers: { authorization: "Bearer ${spec.token}" }, body: { id: "${spec.stageId}", value: ${spec.ordinal}, values: [1, 2, 3], mode: "sum" } }, 404, "not_found"],
    ["invalid-mode", { method: "POST", path: "${spec.route}", headers: { authorization: "Bearer ${spec.token}" }, body: { id: "${spec.stageId}", value: ${spec.ordinal}, values: [1, 2, 3], mode: "avg" } }, 400, "bad_request"],
    ["short-values", { method: "POST", path: "${spec.route}", headers: { authorization: "Bearer ${spec.token}" }, body: { id: "${spec.stageId}", value: ${spec.ordinal}, values: [1, 2], mode: "sum" } }, 400, "bad_request"],
    ["noninteger-value", { method: "POST", path: "${spec.route}", headers: { authorization: "Bearer ${spec.token}" }, body: { id: "${spec.stageId}", value: ${spec.ordinal}.5, values: [1, 2, 3], mode: "sum" } }, 400, "bad_request"],
    ["extra-body-field", { method: "POST", path: "${spec.route}", headers: { authorization: "Bearer ${spec.token}" }, body: { id: "${spec.stageId}", value: ${spec.ordinal}, values: [1, 2, 3], mode: "sum", extra: true } }, 400, "bad_request"],
  ];
  for (const [label, request, status, error] of badCases) {
    const response = handler(request);
    if (response?.status !== status || response?.body?.error !== error) {
      console.error(label + ": expected " + status + "/" + error + ", got " + response?.status + "/" + response?.body?.error);
      process.exit(1);
    }
  }
}).catch((error)=>{ console.error(error?.stack || error?.message || String(error)); process.exit(1); })
`;
  return `node -e ${JSON.stringify(script.replace(/\s+/gu, " ").trim())}`;
}

function basicFunctionName(ordinal) {
  return `stage${String(ordinal).padStart(2, "0")}`;
}

function apiFunctionName(ordinal) {
  return `handleStage${String(ordinal).padStart(2, "0")}`;
}

function yamlSingle(value) {
  return `'${value.replace(/'/gu, "''")}'`;
}

function parseArgs(argv) {
  const parsed = {};
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--out" || arg === "--stages" || arg === "--profile") {
      const value = argv[index + 1];
      if (!value) throw new Error(`${arg} requires a value`);
      parsed[arg.slice(2)] = value;
      index += 1;
    } else {
      throw new Error(`unknown argument: ${arg}`);
    }
  }
  return parsed;
}
